apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: first_env_cka
  version: "1.16"
nodeGroups:
  - name: nodegroup1
    instanceType: t2.micro
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    volumeSize: 8
    
